version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: redislabsmodules/rmbuilder:latest

    steps:
      - checkout

      - run:
          name: get tools
          command: |
            apt-get -y update
            apt-get -y install python3 python3-pip python3-venv pylint3

      # Download and cache python module dependencies (esp. latest redis)
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run check
          command: |
            . venv/bin/activate
            find rmtest -name \*.py | \
            while read file; do echo $file; pylint3 $file; done

      - run:
          name: run build
          command: |
            . venv/bin/activate
            python3 setup.py build

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 setup.py test
