version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: redislabsmodules/rmbuilder:latest

    steps:
      - checkout

      - run:
          name: update python toolchain
          command: |
            sudo apt-get update
            sudo apt-get install python3 pylint3 pip3

      # Download and cache dependencies (use latest python modules)
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run check
          command: |
            find rmtest -name \*.py | \
            while read file; do echo $file; pylint3 $file; done

      - run:
          name: run build
          command: python3 setup.py build

      - run:
          name: run tests
          command: python3 setup.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
