version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: redislabsmodules/rmbuilder:latest

    steps:
      - checkout

      - run:
          name: Get toolchain
          command: |
            apt-get -y update
            apt-get -y install python3 python3-redis python3-setuptools pylint3

      - run:
          name: Run check
          command: |
            find rmtest -name \*.py | \
            while read file; do echo $file; pylint3 $file; done

      - run:
          name: Run build
          command: python3 setup.py build

#      Currently we cannot run tests because we do not have a version of
#      the python3-redis package available with cluster support.
#     - run:
#         name: Run tests
#         command: python3 setup.py test
