version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/python:latest
      - image: gcc:latest

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run build
          command: python3 setup.py build

      - run:
          name: run tests
          command: python3 setup.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
