version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: redislabsmodules/rmbuilder:latest

    steps:
      - checkout

      - run:
          name: toolchain
          command: |
            apt-get -y update
            apt-get -y install python3 python3-redis pylint3

      - run:
          name: run check
          command: |
            find rmtest -name \*.py | \
            while read file; do echo $file; pylint3 $file; done

      - run:
          name: run build
          command: python3 setup.py build

      - run:
          name: run tests
          command: python3 setup.py test
