version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: redislabsmodules/rmbuilder:latest

    steps:
      - checkout

#      - run:
#          name: run check
#          command: |
#            find rmtest -name \*.py | \
#            while read file; do echo $file; pylint3 $file; done

      - run:
          name: run build
          command: python setup.py build

      - run:
          name: run tests
          command: python setup.py test
